# Generated by Django 3.2.7 on 2023-08-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('no_of_products', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
