# Generated by Django 3.2.7 on 2023-08-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_products', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
