# Generated by Django 3.2.7 on 2023-08-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_customplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customplan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
