# Generated by Django 3.2.7 on 2023-08-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_customplan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customplan',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
