# Generated by Django 3.2.7 on 2023-08-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_alter_customplan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customplan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
